import React from "react";
import { StyledList, StyledItem, StyledNav } from "./NavBar.styled";
import { Link } from "react-scroll";

export const NavBar = ({ toggle }) => {
  return (
    <StyledNav>
      <StyledList>
        <StyledItem>
          <Link
            onClick={toggle}
            to="about"
            spy={true}
            smooth={true}
            offset={-150}
            duration={500}
          >
            About
          </Link>
        </StyledItem>
        <StyledItem>
          <Link
            onClick={toggle}
            to="partners"
            spy={true}
            smooth={true}
            offset={-70}
            duration={500}
          >
            Partners
          </Link>
        </StyledItem>
        <StyledItem>
          <Link
            onClick={toggle}
            to="blog"
            spy={true}
            smooth={true}
            offset={600}
            duration={500}
          >
            Information
          </Link>
        </StyledItem>
        <StyledItem>
          <Link
            onClick={toggle}
            to="news"
            spy={true}
            smooth={true}
            offset={-70}
            duration={500}
          >
            News
          </Link>
        </StyledItem>
        <StyledItem>
          <Link
            onClick={toggle}
            to="map"
            spy={true}
            smooth={true}
            offset={-70}
            duration={500}
          >
            Map
          </Link>
        </StyledItem>
      </StyledList>
    </StyledNav>
  );
};
